name: module3_task0
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  module3_task0:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout
