---
name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  module3_task0:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.91.2"
          extended: true
      - name: lint
        run: make lint
      - name: build
        run: make build
      - name: post
        run: make POST_TITLE="Test Title" POST_NAME="Test-name" post
      - name: Integration tests
        run: make integration-tests
      - name: clean
        run: make clean
